In [2]:
import pandas as pd
import numpy as np
import os

import sys
NFL_STATS_DIR = r'..\\'
sys.path.append(NFL_STATS_DIR)
import nfl_stats_scraper_constants as nssc

# Initialize data sets using created methods

In [1]:
import aml_pipeline_methods as aml

In [3]:
#
# Read in the csv data
#
df_train, df_validate, df_test = aml.pull_train_validate_test_datasets(aml.TRAIN_CSV, aml.VALIDATE_CSV, aml.TEST_CSV)

In [4]:
#
# Drop unwanted features/columns
#
df_train_o, df_validate_o, df_test_o = aml.remove_special_cols(df_train, df_validate, df_test)

INFO: col set start size, 932
INFO: col set after removed kicking, 852
INFO: col set after removed returns, 752
INFO: col set after removed last 5 games, 600
INFO: col set after removed Second Quarter Pts, 584
INFO: col set after removed Third Quarter, 568
INFO: col set after removed player offense, 388
INFO: Length of df train (2880, 388)
INFO: Length of df validate (720, 388)
INFO: Length of df test (721, 388)

In [5]:
#
# Replace NaN Values with Zero
#
df_train_o, df_validate_o, df_test_o = aml.replace_any_nan_values(df_train_o, df_validate_o, df_test_o)

Found a difference for validate Away Avg. First Quarter Pts Scored last 1 games, 720 vs 719
Found a difference for validate Away Avg. First Quarter Pts Scored last 2 games, 720 vs 719
Found a difference for validate Away Avg. First Quarter Pts Scored last 3 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Scored last 1 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Scored last 2 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Scored last 3 games, 720 vs 719
Found a difference for validate Away Avg. Final Score last 1 games, 720 vs 719
Found a difference for validate Away Avg. Final Score last 2 games, 720 vs 719
Found a difference for validate Away Avg. Final Score last 3 games, 720 vs 719
Found a difference for validate Away Avg. First Quarter Pts Gave Up last 1 games, 720 vs 719
Found a difference for validate Away Avg. First Quarter Pts Gave Up last 2 games, 720 vs 719
Found a difference for validate Away Avg. First Quarter Pts Gave Up last 3 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Gave Up last 1 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Gave Up last 2 games, 720 vs 719
Found a difference for validate Away Avg. Fourth Quarter Pts Gave Up last 3 games, 720 vs 719
Found a difference for validate Away Avg. Total Points Gave Up last 1 games, 720 vs 719
Found a difference for validate Away Avg. Total Points Gave Up last 2 games, 720 vs 719
Found a difference for validate Away Avg. Total Points Gave Up last 3 games, 720 vs 719
Found a difference for validate Away Avg. Won Game last 1 games, 720 vs 719
Found a difference for validate Away Avg. Won Game last 2 games, 720 vs 719
Found a difference for validate Away Avg. Won Game last 3 games, 720 vs 719
Found a difference for validate Away Avg. First Downs last 1 games, 720 vs 719
Found a difference for validate Away Avg. First Downs last 2 games, 720 vs 719
Found a difference for validate Away Avg. First Downs last 3 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Attemtps last 1 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Attemtps last 2 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Attemtps last 3 games, 720 vs 719
Found a difference for validate Away Avg. Passing INTs last 1 games, 720 vs 719
Found a difference for validate Away Avg. Passing INTs last 2 games, 720 vs 719
Found a difference for validate Away Avg. Passing INTs last 3 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks last 1 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks last 2 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks last 3 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Offensive Sacks Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Net Pass Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Net Pass Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Net Pass Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Total Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Total Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Total Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles last 1 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles last 2 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles last 3 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles Lost last 1 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles Lost last 2 games, 720 vs 719
Found a difference for validate Away Avg. Team Fumbles Lost last 3 games, 720 vs 719
Found a difference for validate Away Avg. Turnovers last 1 games, 720 vs 719
Found a difference for validate Away Avg. Turnovers last 2 games, 720 vs 719
Found a difference for validate Away Avg. Turnovers last 3 games, 720 vs 719
Found a difference for validate Away Avg. Penalties last 1 games, 720 vs 719
Found a difference for validate Away Avg. Penalties last 2 games, 720 vs 719
Found a difference for validate Away Avg. Penalties last 3 games, 720 vs 719
Found a difference for validate Away Avg. Penalty Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Penalty Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Penalty Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Attempts last 1 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Attempts last 2 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Attempts last 3 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Successes last 1 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Successes last 2 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Successes last 3 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Attempts last 1 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Attempts last 2 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Attempts last 3 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Successes last 1 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Successes last 2 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Successes last 3 games, 720 vs 719
Found a difference for validate Away Avg. Time of Possession last 1 games, 720 vs 719
Found a difference for validate Away Avg. Time of Possession last 2 games, 720 vs 719
Found a difference for validate Away Avg. Time of Possession last 3 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. 3rd Down Conversion Rate last 3 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. 4th Down Conversion Rate last 3 games, 720 vs 719
Found a difference for validate Away Avg. Passing Completion Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. Passing Completion Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. Passing Completion Rate last 3 games, 720 vs 719
Found a difference for validate Away Avg. Passing Long last 1 games, 720 vs 719
Found a difference for validate Away Avg. Passing Long last 2 games, 720 vs 719
Found a difference for validate Away Avg. Passing Long last 3 games, 720 vs 719
Found a difference for validate Away Avg. Passing Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. Passing Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. Passing Rate last 3 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Long last 1 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Long last 2 games, 720 vs 719
Found a difference for validate Away Avg. Rushing Long last 3 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles last 1 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles last 2 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles last 3 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles Yards Loss last 1 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles Yards Loss last 2 games, 720 vs 719
Found a difference for validate Away Avg. Offense Fumbles Yards Loss last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions TDs last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions TDs last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions TDs last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Long Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Long Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Interceptions Long Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Pass Deflections last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Pass Deflections last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Pass Deflections last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Sacks last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Sacks last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Sacks last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles Combined last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles Combined last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles Combined last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Solo Tackles last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Solo Tackles last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Solo Tackles last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackle Assists last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackle Assists last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackle Assists last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles for Loss last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles for Loss last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Tackles for Loss last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense QB Hits last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense QB Hits last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense QB Hits last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Recovered last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Recovered last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Recovered last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Yards last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Yards last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles Yards last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles TDs last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles TDs last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Fumbles TDs last 3 games, 720 vs 719
Found a difference for validate Away Avg. Defense Forced Fumbles last 1 games, 720 vs 719
Found a difference for validate Away Avg. Defense Forced Fumbles last 2 games, 720 vs 719
Found a difference for validate Away Avg. Defense Forced Fumbles last 3 games, 720 vs 719
Found a difference for validate Away Avg. Extra Point Success Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. Extra Point Success Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. Extra Point Success Rate last 3 games, 720 vs 719
Found a difference for validate Away Avg. Field Goal Success Rate last 1 games, 720 vs 719
Found a difference for validate Away Avg. Field Goal Success Rate last 2 games, 720 vs 719
Found a difference for validate Away Avg. Field Goal Success Rate last 3 games, 720 vs 719
Found a difference for test Away Avg. First Quarter Pts Scored last 1 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Scored last 1 games, 721 vs 718
Found a difference for test Away Avg. First Quarter Pts Scored last 2 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Scored last 2 games, 721 vs 718
Found a difference for test Away Avg. First Quarter Pts Scored last 3 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Scored last 3 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Scored last 1 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Scored last 1 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Scored last 2 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Scored last 2 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Scored last 3 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Scored last 3 games, 721 vs 718
Found a difference for test Away Avg. Final Score last 1 games, 721 vs 719
Found a difference for test Home Avg. Final Score last 1 games, 721 vs 718
Found a difference for test Away Avg. Final Score last 2 games, 721 vs 719
Found a difference for test Home Avg. Final Score last 2 games, 721 vs 718
Found a difference for test Away Avg. Final Score last 3 games, 721 vs 719
Found a difference for test Home Avg. Final Score last 3 games, 721 vs 718
Found a difference for test Away Avg. First Quarter Pts Gave Up last 1 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Gave Up last 1 games, 721 vs 718
Found a difference for test Away Avg. First Quarter Pts Gave Up last 2 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Gave Up last 2 games, 721 vs 718
Found a difference for test Away Avg. First Quarter Pts Gave Up last 3 games, 721 vs 719
Found a difference for test Home Avg. First Quarter Pts Gave Up last 3 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Gave Up last 1 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Gave Up last 1 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Gave Up last 2 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Gave Up last 2 games, 721 vs 718
Found a difference for test Away Avg. Fourth Quarter Pts Gave Up last 3 games, 721 vs 719
Found a difference for test Home Avg. Fourth Quarter Pts Gave Up last 3 games, 721 vs 718
Found a difference for test Away Avg. Total Points Gave Up last 1 games, 721 vs 719
Found a difference for test Home Avg. Total Points Gave Up last 1 games, 721 vs 718
Found a difference for test Away Avg. Total Points Gave Up last 2 games, 721 vs 719
Found a difference for test Home Avg. Total Points Gave Up last 2 games, 721 vs 718
Found a difference for test Away Avg. Total Points Gave Up last 3 games, 721 vs 719
Found a difference for test Home Avg. Total Points Gave Up last 3 games, 721 vs 718
Found a difference for test Away Avg. Won Game last 1 games, 721 vs 719
Found a difference for test Home Avg. Won Game last 1 games, 721 vs 718
Found a difference for test Away Avg. Won Game last 2 games, 721 vs 719
Found a difference for test Home Avg. Won Game last 2 games, 721 vs 718
Found a difference for test Away Avg. Won Game last 3 games, 721 vs 719
Found a difference for test Home Avg. Won Game last 3 games, 721 vs 718
Found a difference for test Away Avg. First Downs last 1 games, 721 vs 719
Found a difference for test Home Avg. First Downs last 1 games, 721 vs 718
Found a difference for test Away Avg. First Downs last 2 games, 721 vs 719
Found a difference for test Home Avg. First Downs last 2 games, 721 vs 718
Found a difference for test Away Avg. First Downs last 3 games, 721 vs 719
Found a difference for test Home Avg. First Downs last 3 games, 721 vs 718
Found a difference for test Away Avg. Rushing Attemtps last 1 games, 721 vs 719
Found a difference for test Home Avg. Rushing Attemtps last 1 games, 721 vs 718
Found a difference for test Away Avg. Rushing Attemtps last 2 games, 721 vs 719
Found a difference for test Home Avg. Rushing Attemtps last 2 games, 721 vs 718
Found a difference for test Away Avg. Rushing Attemtps last 3 games, 721 vs 719
Found a difference for test Home Avg. Rushing Attemtps last 3 games, 721 vs 718
Found a difference for test Away Avg. Passing INTs last 1 games, 721 vs 719
Found a difference for test Home Avg. Passing INTs last 1 games, 721 vs 718
Found a difference for test Away Avg. Passing INTs last 2 games, 721 vs 719
Found a difference for test Home Avg. Passing INTs last 2 games, 721 vs 718
Found a difference for test Away Avg. Passing INTs last 3 games, 721 vs 719
Found a difference for test Home Avg. Passing INTs last 3 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks last 1 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks last 1 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks last 2 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks last 2 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks last 3 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks last 3 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks Yards last 1 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks Yards last 1 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks Yards last 2 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks Yards last 2 games, 721 vs 718
Found a difference for test Away Avg. Offensive Sacks Yards last 3 games, 721 vs 719
Found a difference for test Home Avg. Offensive Sacks Yards last 3 games, 721 vs 718
Found a difference for test Away Avg. Net Pass Yards last 1 games, 721 vs 719
Found a difference for test Home Avg. Net Pass Yards last 1 games, 721 vs 718
Found a difference for test Away Avg. Net Pass Yards last 2 games, 721 vs 719
Found a difference for test Home Avg. Net Pass Yards last 2 games, 721 vs 718
Found a difference for test Away Avg. Net Pass Yards last 3 games, 721 vs 719
Found a difference for test Home Avg. Net Pass Yards last 3 games, 721 vs 718
Found a difference for test Away Avg. Total Yards last 1 games, 721 vs 719
Found a difference for test Home Avg. Total Yards last 1 games, 721 vs 718
Found a difference for test Away Avg. Total Yards last 2 games, 721 vs 719
Found a difference for test Home Avg. Total Yards last 2 games, 721 vs 718
Found a difference for test Away Avg. Total Yards last 3 games, 721 vs 719
Found a difference for test Home Avg. Total Yards last 3 games, 721 vs 718
Found a difference for test Away Avg. Team Fumbles last 1 games, 721 vs 719
Found a difference for test Home Avg. Team Fumbles last 1 games, 721 vs 718
Found a difference for test Away Avg. Team Fumbles last 2 games, 721 vs 719
Found a difference for test Home Avg. Team Fumbles last 2 games, 721 vs 718

In [6]:
#
# Get the features-label sets for train, validate and test
#
x_train, y_train, x_validate, y_validate, x_test, y_test = aml.get_feature_labels_train_validate_test_sets(df_train_o, df_validate_o, df_test_o)

INFO: The shape of the training feature set is (2880, 383)
INFO: The shape of the training labels is (2880,)
INFO: The shape of the validate feature set is (720, 383)
INFO: The shape of the validate labels is (720,)
INFO: The shape of the test feature set is (721, 383)
INFO: The shape of the test labels is (721,)

In [7]:
#
# Normalize the feature sets
#
x_train_norm, x_validate_norm, x_test_norm = aml.normalize_test_validate_train_sets(x_train, x_test, x_validate)

# Sandbox work start

In [2]:
TEST_CSV = r"C:\Users\cocod\Work\Repos\NFL_stats_tracker\stats\season_datasets\raw_combined_datasets\test_dataset.csv"
VALIDATE_CSV = r"C:\Users\cocod\Work\Repos\NFL_stats_tracker\stats\season_datasets\raw_combined_datasets\validate_dataset.csv"
TRAIN_CSV = r"C:\Users\cocod\Work\Repos\NFL_stats_tracker\stats\season_datasets\raw_combined_datasets\train_dataset.csv"

In [3]:
def read_train_test_validate_datasets(train_csv:str, validate_csv:str,
                                     test_csv:str):
    if not os.path.exists(train_csv):
        print(f'ERROR: the train dataset does not exist, {train_csv}\n')
    
    if not os.path.exists(validate_csv):
        print(f'ERROR: the validate dataset does not exist, {validate_csv}\n')
    
    if not os.path.exists(test_csv):
        print(f'ERROR: the test dataset does not exist, {test_csv}\n')
    
    df_train = pd.read_csv(train_csv)
    df_validate = pd.read_csv(validate_csv)
    df_test = pd.read_csv(test_csv)
    
    return df_train, df_validate, df_test

In [4]:
df_train, df_validate, df_test = read_train_test_validate_datasets(TRAIN_CSV, VALIDATE_CSV, TEST_CSV)

In [5]:
df_train

,Year,Week,Game Index,Home Team,Away Team,Away First Quarter Pts Scored season,Home First Quarter Pts Scored season,Away Avg. First Quarter Pts Scored last 1 games,Home Avg. First Quarter Pts Scored last 1 games,Away Avg. First Quarter Pts Scored last 2 games,...,Home Punt Return Long Yards season,Away Avg. Punt Return Long Yards last 1 games,Home Avg. Punt Return Long Yards last 1 games,Away Avg. Punt Return Long Yards last 2 games,Home Avg. Punt Return Long Yards last 2 games,Away Avg. Punt Return Long Yards last 3 games,Home Avg. Punt Return Long Yards last 3 games,Away Avg. Punt Return Long Yards last 5 games,Home Avg. Punt Return Long Yards last 5 games,Winning Team
0,2002,2,0,MIA,IND,7,7,7.0,7.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,1
1,2002,2,1,JAX,KAN,7,0,7.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,1
2,2002,2,2,TEN,DAL,0,7,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0
3,2002,2,3,TAM,BAL,7,0,7.0,0.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,1
4,2002,2,4,CIN,CLE,6,0,6.0,0.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2875,2013,17,11,BUF,NWE,68,70,14.0,3.0,8.5,...,166.0,11.0,7.0,5.5,5.0,6.333333,10.333333,10.0,12.0,0
2876,2013,17,12,DEN,OAK,89,116,0.0,3.0,1.5,...,213.0,0.0,8.0,3.0,4.0,2.000000,6.000000,6.4,7.0,1
2877,2013,17,13,KAN,SDG,54,110,3.0,7.0,3.0,...,368.0,28.0,25.0,17.0,17.0,12.000000,36.000000,8.2,25.2,0
2878,2013,17,14,STL,SEA,62,67,0.0,0.0,1.5,...,224.0,29.0,15.0,25.5,11.0,29.666667,7.666667,22.4,6.8,0
2879,2013,17,15,PHI,DAL,91,86,7.0,21.0,10.0,...,128.0,62.0,5.0,34.5,3.0,23.000000,2.000000,18.6,4.0,1

# Filter the features/columns

In [6]:
kicking_cols = [val[0][3:] for val in nssc.KICKING_COLUMN_MAP.values()]
print(kicking_cols)

returns_cols = [val[0][3:] for val in nssc.RETURNS_COLUMN_MAP.values()]
print(returns_cols)

['Extra Points Made', 'Extra Point Attempts', 'Field Goals Made', 'Field Goal Attempts', 'Punts Total', 'Punt Yards Total', 'Punting Yards/Punt', 'Punting Long Yards']
['Kick Return Attempts', 'Kick Return Yards', 'Kick Return Yards Avg', 'Kick Return TDs', 'Kick Return Long Yards', 'Punt Return Attempts', 'Punt Return Yards', 'Punt Return Yards Avg', 'Punt Return TDs', 'Punt Return Long Yards']

In [7]:
master_cols = df_train.columns.to_list().copy()
print(len(master_cols))

932

In [8]:
# remove all kicking
print(kicking_cols)
tgt1_cols = list()
for col in master_cols:
    found_match = False
    for c in kicking_cols:
        if c in col:
            found_match = True
            break
    if not found_match:
        tgt1_cols.append(col)
print(len(tgt1_cols))

['Extra Points Made', 'Extra Point Attempts', 'Field Goals Made', 'Field Goal Attempts', 'Punts Total', 'Punt Yards Total', 'Punting Yards/Punt', 'Punting Long Yards']
852

In [9]:
# remove all returns
print(len(tgt1_cols))
print(returns_cols)
tgt2_cols = list()

for col in tgt1_cols:
    found_match = False
    for c in returns_cols:
        if c in col:
            found_match = True
            break
    if not found_match:
        tgt2_cols.append(col)
print(len(tgt2_cols))

852
['Kick Return Attempts', 'Kick Return Yards', 'Kick Return Yards Avg', 'Kick Return TDs', 'Kick Return Long Yards', 'Punt Return Attempts', 'Punt Return Yards', 'Punt Return Yards Avg', 'Punt Return TDs', 'Punt Return Long Yards']
752

In [10]:
# remove last 5 games
s = 'last 5 games'
tgt3_cols = [col for col in tgt2_cols if not(s in col)]
print(f'INFO: col set after removed last 5 games, {len(tgt3_cols)}')

INFO: col set after removed last 5 games, 600

In [11]:
# remove Second Quarter
s2nd = 'Second Quarter Pts'
tgt4_cols = [col for col in tgt3_cols if not(s2nd in col)]
print(f'INFO: col set after removed {s2nd}, {len(tgt4_cols)}')

INFO: col set after removed Second Quarter Pts, 584

In [12]:
# remove Third Quarter
s3rd = 'Third Quarter'
tgt5_cols = [col for col in tgt4_cols if not(s3rd in col)]
print(f'INFO: col set after removed {s3rd}, {len(tgt5_cols)}')

INFO: col set after removed Third Quarter, 568

In [13]:
cols_po = [val[0][3:] for val in nssc.PLAYER_OFFENSE_COLUMN_MAP.values()]
cols_po

po_cols_keep = ['Passing Long', 'Passing Rate', 'Rushing Long',  'Offense Fumbles', 'Offense Fumbles Yards Loss']

print(f'INFO: the original size of the player offense columns is {len(cols_po)}')
for col in po_cols_keep:
    cols_po.remove(col)
print(f'INFO: the reduced size of the player offense columns is {len(cols_po)}')

INFO: the original size of the player offense columns is 20
INFO: the reduced size of the player offense columns is 15

In [14]:
# remove redundant player offense columns/features
print(len(tgt5_cols))
tgt6_cols = list()

for col in tgt5_cols:
    found_match = False
    for c in cols_po:
        if c in col:
            found_match = True
            break
    if not found_match:
        tgt6_cols.append(col)
print(len(tgt6_cols))

568
388

In [21]:
df_train_red = df_train[tgt6_cols]

In [22]:
df_validate_red = df_validate[tgt6_cols]

In [23]:
df_test_red = df_test[tgt6_cols]
df_test_red

,Year,Week,Game Index,Home Team,Away Team,Away First Quarter Pts Scored season,Home First Quarter Pts Scored season,Away Avg. First Quarter Pts Scored last 1 games,Home Avg. First Quarter Pts Scored last 1 games,Away Avg. First Quarter Pts Scored last 2 games,...,Home Avg. Extra Point Success Rate last 2 games,Away Avg. Extra Point Success Rate last 3 games,Home Avg. Extra Point Success Rate last 3 games,Away Avg. Field Goal Success Rate last 1 games,Home Avg. Field Goal Success Rate last 1 games,Away Avg. Field Goal Success Rate last 2 games,Home Avg. Field Goal Success Rate last 2 games,Away Avg. Field Goal Success Rate last 3 games,Home Avg. Field Goal Success Rate last 3 games,Winning Team
0,2017,2,0,HOU,CIN,0.0,0.0,0.0,0.0,0.0,...,1.00,0.000000,1.000000,0.00,0.000000,0.00,0.000000,0.000000,0.000000,1
1,2017,2,1,BUF,CAR,7.0,0.0,7.0,0.0,7.0,...,1.00,1.000000,1.000000,1.00,0.000000,1.00,0.000000,1.000000,0.000000,0
2,2017,2,2,ARI,IND,3.0,10.0,3.0,10.0,3.0,...,1.00,0.000000,1.000000,0.50,0.500000,0.50,0.500000,0.500000,0.500000,1
3,2017,2,3,TEN,JAX,3.0,7.0,3.0,7.0,3.0,...,1.00,0.666667,1.000000,0.75,0.750000,0.75,0.750000,0.750000,0.750000,1
4,2017,2,4,PHI,KAN,7.0,7.0,7.0,7.0,7.0,...,0.50,1.000000,0.500000,0.00,1.000000,0.00,1.000000,0.000000,1.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,2019,17,11,IND,JAX,57.0,79.0,0.0,14.0,1.5,...,1.00,0.666667,1.000000,1.00,1.000000,1.00,0.500000,1.000000,0.555556,0
717,2019,17,12,PHI,NYG,48.0,66.0,14.0,10.0,7.0,...,1.00,0.933333,1.000000,0.00,0.333333,0.00,0.666667,0.333333,0.611111,1
718,2019,17,13,ARI,LAR,49.0,70.0,7.0,7.0,3.5,...,1.00,1.000000,1.000000,0.50,0.666667,0.25,0.833333,0.166667,0.888889,0
719,2019,17,14,PIT,BAL,122.0,47.0,0.0,0.0,6.5,...,1.00,0.933333,1.000000,1.00,1.000000,0.50,1.000000,0.666667,1.000000,0
720,2019,17,15,SFO,SEA,77.0,93.0,7.0,3.0,10.0,...,0.75,0.583333,0.833333,1.00,1.000000,1.00,1.000000,1.000000,1.000000,1

# Verify there are not any nan values

In [24]:
for col in df_validate_red.columns:
    lorig = len(df_validate_red[col])
    ldrop = len(df_validate_red[col].dropna())
    if lorig != ldrop:
        print(f'Found a difference for {col}, {lorig} vs {ldrop}')
        df_validate_red[col] = df_validate_red[col].fillna(0)

Found a difference for Away Avg. First Quarter Pts Scored last 1 games, 720 vs 719
Found a difference for Away Avg. First Quarter Pts Scored last 2 games, 720 vs 719
Found a difference for Away Avg. First Quarter Pts Scored last 3 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Scored last 1 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Scored last 2 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Scored last 3 games, 720 vs 719
Found a difference for Away Avg. Final Score last 1 games, 720 vs 719
Found a difference for Away Avg. Final Score last 2 games, 720 vs 719
Found a difference for Away Avg. Final Score last 3 games, 720 vs 719
Found a difference for Away Avg. First Quarter Pts Gave Up last 1 games, 720 vs 719
Found a difference for Away Avg. First Quarter Pts Gave Up last 2 games, 720 vs 719
Found a difference for Away Avg. First Quarter Pts Gave Up last 3 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 1 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 2 games, 720 vs 719
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 3 games, 720 vs 719
Found a difference for Away Avg. Total Points Gave Up last 1 games, 720 vs 719
Found a difference for Away Avg. Total Points Gave Up last 2 games, 720 vs 719
Found a difference for Away Avg. Total Points Gave Up last 3 games, 720 vs 719
Found a difference for Away Avg. Won Game last 1 games, 720 vs 719
Found a difference for Away Avg. Won Game last 2 games, 720 vs 719
Found a difference for Away Avg. Won Game last 3 games, 720 vs 719
Found a difference for Away Avg. First Downs last 1 games, 720 vs 719
Found a difference for Away Avg. First Downs last 2 games, 720 vs 719
Found a difference for Away Avg. First Downs last 3 games, 720 vs 719
Found a difference for Away Avg. Rushing Attemtps last 1 games, 720 vs 719
Found a difference for Away Avg. Rushing Attemtps last 2 games, 720 vs 719
Found a difference for Away Avg. Rushing Attemtps last 3 games, 720 vs 719
Found a difference for Away Avg. Passing INTs last 1 games, 720 vs 719
Found a difference for Away Avg. Passing INTs last 2 games, 720 vs 719
Found a difference for Away Avg. Passing INTs last 3 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks last 1 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks last 2 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks last 3 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Offensive Sacks Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Net Pass Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Net Pass Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Net Pass Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Total Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Total Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Total Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles last 1 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles last 2 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles last 3 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles Lost last 1 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles Lost last 2 games, 720 vs 719
Found a difference for Away Avg. Team Fumbles Lost last 3 games, 720 vs 719
Found a difference for Away Avg. Turnovers last 1 games, 720 vs 719
Found a difference for Away Avg. Turnovers last 2 games, 720 vs 719
Found a difference for Away Avg. Turnovers last 3 games, 720 vs 719
Found a difference for Away Avg. Penalties last 1 games, 720 vs 719
Found a difference for Away Avg. Penalties last 2 games, 720 vs 719
Found a difference for Away Avg. Penalties last 3 games, 720 vs 719
Found a difference for Away Avg. Penalty Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Penalty Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Penalty Yards last 3 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Attempts last 1 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Attempts last 2 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Attempts last 3 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Successes last 1 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Successes last 2 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Successes last 3 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Attempts last 1 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Attempts last 2 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Attempts last 3 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Successes last 1 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Successes last 2 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Successes last 3 games, 720 vs 719
Found a difference for Away Avg. Time of Possession last 1 games, 720 vs 719
Found a difference for Away Avg. Time of Possession last 2 games, 720 vs 719
Found a difference for Away Avg. Time of Possession last 3 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Rate last 1 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Rate last 2 games, 720 vs 719
Found a difference for Away Avg. 3rd Down Conversion Rate last 3 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Rate last 1 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Rate last 2 games, 720 vs 719
Found a difference for Away Avg. 4th Down Conversion Rate last 3 games, 720 vs 719
Found a difference for Away Avg. Passing Completion Rate last 1 games, 720 vs 719
Found a difference for Away Avg. Passing Completion Rate last 2 games, 720 vs 719
Found a difference for Away Avg. Passing Completion Rate last 3 games, 720 vs 719
Found a difference for Away Avg. Passing Long last 1 games, 720 vs 719
Found a difference for Away Avg. Passing Long last 2 games, 720 vs 719
Found a difference for Away Avg. Passing Long last 3 games, 720 vs 719
Found a difference for Away Avg. Passing Rate last 1 games, 720 vs 719
Found a difference for Away Avg. Passing Rate last 2 games, 720 vs 719
Found a difference for Away Avg. Passing Rate last 3 games, 720 vs 719
Found a difference for Away Avg. Rushing Long last 1 games, 720 vs 719
Found a difference for Away Avg. Rushing Long last 2 games, 720 vs 719
Found a difference for Away Avg. Rushing Long last 3 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles last 1 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles last 2 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles last 3 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles Yards Loss last 1 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles Yards Loss last 2 games, 720 vs 719
Found a difference for Away Avg. Offense Fumbles Yards Loss last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions TDs last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions TDs last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions TDs last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Long Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Long Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Interceptions Long Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Pass Deflections last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Pass Deflections last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Pass Deflections last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Sacks last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Sacks last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Sacks last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles Combined last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles Combined last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles Combined last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Solo Tackles last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Solo Tackles last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Solo Tackles last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Tackle Assists last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Tackle Assists last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Tackle Assists last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles for Loss last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles for Loss last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Tackles for Loss last 3 games, 720 vs 719
Found a difference for Away Avg. Defense QB Hits last 1 games, 720 vs 719
Found a difference for Away Avg. Defense QB Hits last 2 games, 720 vs 719
Found a difference for Away Avg. Defense QB Hits last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Recovered last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Recovered last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Recovered last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Yards last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Yards last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles Yards last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles TDs last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles TDs last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Fumbles TDs last 3 games, 720 vs 719
Found a difference for Away Avg. Defense Forced Fumbles last 1 games, 720 vs 719
Found a difference for Away Avg. Defense Forced Fumbles last 2 games, 720 vs 719
Found a difference for Away Avg. Defense Forced Fumbles last 3 games, 720 vs 719
Found a difference for Away Avg. Extra Point Success Rate last 1 games, 720 vs 719
Found a difference for Away Avg. Extra Point Success Rate last 2 games, 720 vs 719
Found a difference for Away Avg. Extra Point Success Rate last 3 games, 720 vs 719
Found a difference for Away Avg. Field Goal Success Rate last 1 games, 720 vs 719
Found a difference for Away Avg. Field Goal Success Rate last 2 games, 720 vs 719
Found a difference for Away Avg. Field Goal Success Rate last 3 games, 720 vs 719

<ipython-input-24-68b291d93089>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_validate_red[col] = df_validate_red[col].fillna(0)

In [25]:
for col in df_test_red.columns:
    lorig = len(df_test_red[col])
    ldrop = len(df_test_red[col].dropna())
    if lorig != ldrop:
        print(f'Found a difference for {col}, {lorig} vs {ldrop}')
        df_test_red[col] = df_test_red[col].fillna(0)

Found a difference for Away Avg. First Quarter Pts Scored last 1 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Scored last 1 games, 721 vs 718
Found a difference for Away Avg. First Quarter Pts Scored last 2 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Scored last 2 games, 721 vs 718
Found a difference for Away Avg. First Quarter Pts Scored last 3 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Scored last 3 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Scored last 1 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Scored last 1 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Scored last 2 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Scored last 2 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Scored last 3 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Scored last 3 games, 721 vs 718
Found a difference for Away Avg. Final Score last 1 games, 721 vs 719
Found a difference for Home Avg. Final Score last 1 games, 721 vs 718
Found a difference for Away Avg. Final Score last 2 games, 721 vs 719
Found a difference for Home Avg. Final Score last 2 games, 721 vs 718
Found a difference for Away Avg. Final Score last 3 games, 721 vs 719
Found a difference for Home Avg. Final Score last 3 games, 721 vs 718
Found a difference for Away Avg. First Quarter Pts Gave Up last 1 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Gave Up last 1 games, 721 vs 718
Found a difference for Away Avg. First Quarter Pts Gave Up last 2 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Gave Up last 2 games, 721 vs 718
Found a difference for Away Avg. First Quarter Pts Gave Up last 3 games, 721 vs 719
Found a difference for Home Avg. First Quarter Pts Gave Up last 3 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 1 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Gave Up last 1 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 2 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Gave Up last 2 games, 721 vs 718
Found a difference for Away Avg. Fourth Quarter Pts Gave Up last 3 games, 721 vs 719
Found a difference for Home Avg. Fourth Quarter Pts Gave Up last 3 games, 721 vs 718
Found a difference for Away Avg. Total Points Gave Up last 1 games, 721 vs 719
Found a difference for Home Avg. Total Points Gave Up last 1 games, 721 vs 718
Found a difference for Away Avg. Total Points Gave Up last 2 games, 721 vs 719
Found a difference for Home Avg. Total Points Gave Up last 2 games, 721 vs 718
Found a difference for Away Avg. Total Points Gave Up last 3 games, 721 vs 719
Found a difference for Home Avg. Total Points Gave Up last 3 games, 721 vs 718
Found a difference for Away Avg. Won Game last 1 games, 721 vs 719
Found a difference for Home Avg. Won Game last 1 games, 721 vs 718
Found a difference for Away Avg. Won Game last 2 games, 721 vs 719
Found a difference for Home Avg. Won Game last 2 games, 721 vs 718
Found a difference for Away Avg. Won Game last 3 games, 721 vs 719
Found a difference for Home Avg. Won Game last 3 games, 721 vs 718
Found a difference for Away Avg. First Downs last 1 games, 721 vs 719
Found a difference for Home Avg. First Downs last 1 games, 721 vs 718
Found a difference for Away Avg. First Downs last 2 games, 721 vs 719
Found a difference for Home Avg. First Downs last 2 games, 721 vs 718
Found a difference for Away Avg. First Downs last 3 games, 721 vs 719
Found a difference for Home Avg. First Downs last 3 games, 721 vs 718
Found a difference for Away Avg. Rushing Attemtps last 1 games, 721 vs 719
Found a difference for Home Avg. Rushing Attemtps last 1 games, 721 vs 718
Found a difference for Away Avg. Rushing Attemtps last 2 games, 721 vs 719
Found a difference for Home Avg. Rushing Attemtps last 2 games, 721 vs 718
Found a difference for Away Avg. Rushing Attemtps last 3 games, 721 vs 719
Found a difference for Home Avg. Rushing Attemtps last 3 games, 721 vs 718
Found a difference for Away Avg. Passing INTs last 1 games, 721 vs 719
Found a difference for Home Avg. Passing INTs last 1 games, 721 vs 718
Found a difference for Away Avg. Passing INTs last 2 games, 721 vs 719
Found a difference for Home Avg. Passing INTs last 2 games, 721 vs 718
Found a difference for Away Avg. Passing INTs last 3 games, 721 vs 719
Found a difference for Home Avg. Passing INTs last 3 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks last 1 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks last 1 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks last 2 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks last 2 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks last 3 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks last 3 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Offensive Sacks Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Offensive Sacks Yards last 3 games, 721 vs 718
Found a difference for Away Avg. Net Pass Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Net Pass Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Net Pass Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Net Pass Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Net Pass Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Net Pass Yards last 3 games, 721 vs 718
Found a difference for Away Avg. Total Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Total Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Total Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Total Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Total Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Total Yards last 3 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles last 1 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles last 1 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles last 2 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles last 2 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles last 3 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles last 3 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles Lost last 1 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles Lost last 1 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles Lost last 2 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles Lost last 2 games, 721 vs 718
Found a difference for Away Avg. Team Fumbles Lost last 3 games, 721 vs 719
Found a difference for Home Avg. Team Fumbles Lost last 3 games, 721 vs 718
Found a difference for Away Avg. Turnovers last 1 games, 721 vs 719
Found a difference for Home Avg. Turnovers last 1 games, 721 vs 718
Found a difference for Away Avg. Turnovers last 2 games, 721 vs 719
Found a difference for Home Avg. Turnovers last 2 games, 721 vs 718
Found a difference for Away Avg. Turnovers last 3 games, 721 vs 719
Found a difference for Home Avg. Turnovers last 3 games, 721 vs 718
Found a difference for Away Avg. Penalties last 1 games, 721 vs 719
Found a difference for Home Avg. Penalties last 1 games, 721 vs 718
Found a difference for Away Avg. Penalties last 2 games, 721 vs 719
Found a difference for Home Avg. Penalties last 2 games, 721 vs 718
Found a difference for Away Avg. Penalties last 3 games, 721 vs 719
Found a difference for Home Avg. Penalties last 3 games, 721 vs 718
Found a difference for Away Avg. Penalty Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Penalty Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Penalty Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Penalty Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Penalty Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Penalty Yards last 3 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Attempts last 1 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Attempts last 1 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Attempts last 2 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Attempts last 2 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Attempts last 3 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Attempts last 3 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Successes last 1 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Successes last 1 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Successes last 2 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Successes last 2 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Successes last 3 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Successes last 3 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Attempts last 1 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Attempts last 1 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Attempts last 2 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Attempts last 2 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Attempts last 3 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Attempts last 3 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Successes last 1 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Successes last 1 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Successes last 2 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Successes last 2 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Successes last 3 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Successes last 3 games, 721 vs 718
Found a difference for Away Avg. Time of Possession last 1 games, 721 vs 719
Found a difference for Home Avg. Time of Possession last 1 games, 721 vs 718
Found a difference for Away Avg. Time of Possession last 2 games, 721 vs 719
Found a difference for Home Avg. Time of Possession last 2 games, 721 vs 718
Found a difference for Away Avg. Time of Possession last 3 games, 721 vs 719
Found a difference for Home Avg. Time of Possession last 3 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Rate last 1 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Rate last 1 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Rate last 2 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Rate last 2 games, 721 vs 718
Found a difference for Away Avg. 3rd Down Conversion Rate last 3 games, 721 vs 719
Found a difference for Home Avg. 3rd Down Conversion Rate last 3 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Rate last 1 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Rate last 1 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Rate last 2 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Rate last 2 games, 721 vs 718
Found a difference for Away Avg. 4th Down Conversion Rate last 3 games, 721 vs 719
Found a difference for Home Avg. 4th Down Conversion Rate last 3 games, 721 vs 718
Found a difference for Away Avg. Passing Completion Rate last 1 games, 721 vs 719
Found a difference for Home Avg. Passing Completion Rate last 1 games, 721 vs 718
Found a difference for Away Avg. Passing Completion Rate last 2 games, 721 vs 719
Found a difference for Home Avg. Passing Completion Rate last 2 games, 721 vs 718
Found a difference for Away Avg. Passing Completion Rate last 3 games, 721 vs 719
Found a difference for Home Avg. Passing Completion Rate last 3 games, 721 vs 718
Found a difference for Away Avg. Passing Long last 1 games, 721 vs 719
Found a difference for Home Avg. Passing Long last 1 games, 721 vs 718
Found a difference for Away Avg. Passing Long last 2 games, 721 vs 719
Found a difference for Home Avg. Passing Long last 2 games, 721 vs 718
Found a difference for Away Avg. Passing Long last 3 games, 721 vs 719
Found a difference for Home Avg. Passing Long last 3 games, 721 vs 718
Found a difference for Away Avg. Passing Rate last 1 games, 721 vs 719
Found a difference for Home Avg. Passing Rate last 1 games, 721 vs 718
Found a difference for Away Avg. Passing Rate last 2 games, 721 vs 719
Found a difference for Home Avg. Passing Rate last 2 games, 721 vs 718
Found a difference for Away Avg. Passing Rate last 3 games, 721 vs 719
Found a difference for Home Avg. Passing Rate last 3 games, 721 vs 718
Found a difference for Away Avg. Rushing Long last 1 games, 721 vs 719
Found a difference for Home Avg. Rushing Long last 1 games, 721 vs 718
Found a difference for Away Avg. Rushing Long last 2 games, 721 vs 719
Found a difference for Home Avg. Rushing Long last 2 games, 721 vs 718
Found a difference for Away Avg. Rushing Long last 3 games, 721 vs 719
Found a difference for Home Avg. Rushing Long last 3 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles last 1 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles last 1 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles last 2 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles last 2 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles last 3 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles last 3 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles Yards Loss last 1 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles Yards Loss last 1 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles Yards Loss last 2 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles Yards Loss last 2 games, 721 vs 718
Found a difference for Away Avg. Offense Fumbles Yards Loss last 3 games, 721 vs 719
Found a difference for Home Avg. Offense Fumbles Yards Loss last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Yards last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions TDs last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions TDs last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions TDs last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions TDs last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions TDs last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions TDs last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Long Yards last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Long Yards last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Long Yards last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Long Yards last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Interceptions Long Yards last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Interceptions Long Yards last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Pass Deflections last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Pass Deflections last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Pass Deflections last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Pass Deflections last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Pass Deflections last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Pass Deflections last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Sacks last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Sacks last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Sacks last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Sacks last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Sacks last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Sacks last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles Combined last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles Combined last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles Combined last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles Combined last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles Combined last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles Combined last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Solo Tackles last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Solo Tackles last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Solo Tackles last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Solo Tackles last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Solo Tackles last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Solo Tackles last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Tackle Assists last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Tackle Assists last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Tackle Assists last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Tackle Assists last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Tackle Assists last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Tackle Assists last 3 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles for Loss last 1 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles for Loss last 1 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles for Loss last 2 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles for Loss last 2 games, 721 vs 718
Found a difference for Away Avg. Defense Tackles for Loss last 3 games, 721 vs 719
Found a difference for Home Avg. Defense Tackles for Loss last 3 games, 721 vs 718
Found a difference for Away Avg. Defense QB Hits last 1 games, 721 vs 719
Found a difference for Home Avg. Defense QB Hits last 1 games, 721 vs 718
Found a difference for Away Avg. Defense QB Hits last 2 games, 721 vs 719

<ipython-input-25-1120d9116b39>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_red[col] = df_test_red[col].fillna(0)

In [26]:
for col in df_train_red.columns:
    lorig = len(df_train_red[col])
    ldrop = len(df_train_red[col].dropna())
    if lorig != ldrop:
        print(f'Found a difference for {col}, {lorig} vs {ldrop}')
        df_train_red[col] = df_train_red[col].fillna(0)

# Get the features and labels

In [27]:
train_cols = df_train_red.columns.to_list().copy()

print(len(train_cols))

388

In [28]:
takeout_cols = ['Year', 'Week', 'Home Team', 'Away Team']
tgt_cols = [col for col in train_cols if not(col in takeout_cols)]

print(len(tgt_cols))
print('Winning Team' in tgt_cols)

384
True

In [29]:
x_cols = [col for col in tgt_cols if 'Winning Team' != col]

print(len(x_cols))
print('Winning Team' in x_cols)

383
False

In [30]:
y_col = ['Winning Team'] # 1 for home team and 0 for away team

In [31]:
x_train = df_train_red[x_cols].to_numpy()
print(x_train.shape)
y_train = df_train_red[y_col].to_numpy().ravel()
print(y_train.shape)

(2880, 383)
(2880,)

In [32]:
x_validate = df_validate_red[x_cols].to_numpy()
print(x_validate.shape)
y_validate = df_validate_red[y_col].to_numpy().ravel()
print(y_validate.shape)

(720, 383)
(720,)

In [33]:
x_test = df_test_red[x_cols].to_numpy()
print(x_test.shape)
y_test = df_test_red[y_col].to_numpy().ravel()
print(y_test.shape)

(721, 383)
(721,)

# Normalize the data

In [34]:
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [36]:
def normalize_train_test_validate_sets(x_train:np.ndarray, x_test:np.ndarray, x_validate:np.ndarray):
    scaler = StandardScaler()
    scaler.fit(x_train)
    x_train_norm = scaler.transform(x_train)
    x_validate_norm = scaler.transform(x_validate)
    x_test_norm = scaler.transform(x_test)
    
    return x_train_norm, x_test_norm, x_validate_norm

In [37]:
x_train_norm, x_test_norm, x_validate_norm = normalize_train_test_validate_sets(x_train, x_test, x_validate)

# Run PCA to reduce the dimension

In [13]:

df_train, df_validate, df_test = aml.replace_any_nan_values(df_train, df_validate, df_test)

x_train_a, y_train_a, x_validate_a, y_validate_a, x_test_a, y_test_a = aml.get_feature_labels_train_validate_test_sets(df_train, df_validate, df_test)

#
# Normalize the feature sets
#
x_train_a_norm, x_validate_a_norm, x_test_a_norm = aml.normalize_test_validate_train_sets(x_train_a, x_test_a, x_validate_a)

INFO: The shape of the training feature set is (2880, 927)
INFO: The shape of the training labels is (2880,)
INFO: The shape of the validate feature set is (720, 927)
INFO: The shape of the validate labels is (720,)
INFO: The shape of the test feature set is (721, 927)
INFO: The shape of the test labels is (721,)

In [39]:
%matplotlib qt
from sklearn.decomposition import PCA
#
# Determine how many components to use
#
pca = PCA().fit(x_train_a_norm)
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('number of components')
plt.ylabel('cumulative explained variance');

In [44]:
v = pca.explained_variance_ratio_
type(v)
print(v.shape)
print(x_train_a_norm.shape)
print(v[:5])

v_csum = np.cumsum(v)
print(v.shape)

(927,)
(2880, 927)
[0.13775379 0.05019769 0.04274947 0.03377253 0.03239478]
(927,)

In [23]:
pca2 = PCA(n_components=300)
pca2.fit(x_train_a_norm)
x_train_a_pca = pca2.transform(x_train_a_norm)
x_train_a_pca.shape

(2880, 300)

In [24]:
x_validate_a_pca = pca2.transform(x_validate_a_norm)
x_validate_a_pca.shape

(720, 300)

In [25]:
x_test_a_pca = pca2.transform(x_test_a_norm)
x_test_a_pca.shape

(721, 300)

In [26]:
clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6144244105409153
Test Set Accuracy: 0.6263888888888889

In [28]:
N_PCA_COMPONENTS = 100
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6074895977808599
Test Set Accuracy: 0.5944444444444444

In [29]:
N_PCA_COMPONENTS = 200
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.608876560332871
Test Set Accuracy: 0.6236111111111111

In [30]:
N_PCA_COMPONENTS = 300
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6158113730929264
Test Set Accuracy: 0.6333333333333333

In [34]:
N_PCA_COMPONENTS = 350
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6116504854368932
Test Set Accuracy: 0.6305555555555555

In [31]:
N_PCA_COMPONENTS = 400
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6102635228848821
Test Set Accuracy: 0.6291666666666667

In [32]:
N_PCA_COMPONENTS = 500
pca = PCA(n_components=N_PCA_COMPONENTS)
pca.fit(x_train_a_norm)

x_train_a_pca = pca.transform(x_train_a_norm)
x_train_a_pca.shape

x_validate_a_pca = pca.transform(x_validate_a_norm)
x_validate_a_pca.shape

x_test_a_pca = pca.transform(x_test_a_norm)
x_test_a_pca.shape

clf_rbf = aml.run_svm_nfl_predict(x_train_a_pca, y_train, 
                        x_test_a_pca, y_test, 
                        x_validate_a_pca, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6047156726768377
Test Set Accuracy: 0.6277777777777778

# Visualize the data using PCA

In [38]:
from sklearn.decomposition import PCA

In [47]:
pca_train = PCA(n_components=2)
principalComponents_x_train = pca_train.fit_transform(x_train_norm)

In [46]:
x_train_norm.shape

(2880, 383)

In [48]:
# create a df out of the data
df_principcal_train = pd.DataFrame(data=principalComponents_x_train, columns=['Principal Component 1', 'Principal Component 2'])

In [41]:
df_principcal_train

      Principal Component 1  Principal Component 2
0                -12.396358              -1.026748
1                -13.013377              -9.651640
2                -12.926700              10.393391
3                -13.024648              -1.941402
4                -13.277628             -12.420219
...                     ...                    ...
2875              15.951331              -2.574325
2876              14.546817               1.689258
2877              12.289751              -1.835064
2878              15.524958               0.995905
2879              14.978250              -0.563165

[2880 rows x 2 columns]

In [49]:
print('Explained variation per principal component: {}'.format(pca_train.explained_variance_ratio_))

Explained variation per principal component: [0.16641627 0.04101544]

In [50]:
import matplotlib.pyplot as plt

In [51]:
plt.figure()
plt.figure(figsize=(10,10))
plt.xticks(fontsize=12)
plt.yticks(fontsize=14)
plt.xlabel('Principal Component - 1',fontsize=20)
plt.ylabel('Principal Component - 2',fontsize=20)
plt.title("Principal Component Analysis of NFL Seasons Dataset",fontsize=20)
targets = [1, 0]
colors = ['r', 'g']
for target, color in zip(targets,colors):
    indicesToKeep = df_train['Winning Team'] == target
    plt.scatter(df_principcal_train.loc[indicesToKeep, 'Principal Component 1']
               , df_principcal_train.loc[indicesToKeep, 'Principal Component 2'], c = color, s = 50)

plt.legend(targets,prop={'size': 15})

# Run SVM

In [45]:
from sklearn import svm       # for the classifier
from sklearn import metrics   # to calculate results

In [46]:
def run_svm_nfl_predict(ix_train:np.ndarray, iy_train:np.ndarray, 
                        ix_test:np.ndarray, iy_test:np.ndarray, 
                        ix_validate:np.ndarray, iy_validate:np.ndarray,
                        kernel_type:str='rbf', C_in:float=1.0):
    # Expects the data to be normalized
    #from sklearn import svm
    #from sklearn import metrics
    
    try:
        #clf = svm.SVC(kernel=kernel_type, cache_size=500)
        clf = svm.SVC(kernel=kernel_type, cache_size=500, C=C_in)
        #clf = svm.SVC(kernel=kernel_type, cache_size=500, probability=True)
    except Exception as e:
        print(f"ERROR: failed to create an svm object for kernel {kernel_type}. Reason -> {e}\n")
        return
    
    # train the classifier
    clf.fit(ix_train, iy_train)
    
    # Run against the validation set
    y_pred_validate = clf.predict(ix_validate)
    print(f'Validate Set Accuracy: {metrics.accuracy_score(iy_validate, y_pred_validate)}')
    
    # Run against the test set
    y_pred_test = clf.predict(ix_test)
    print(f'Test Set Accuracy: {metrics.accuracy_score(iy_test, y_pred_test)}')
    
    return clf

In [48]:
clf_linear = run_svm_nfl_predict(x_train_norm, y_train, 
                        x_test_norm, y_test, 
                        x_validate_norm, y_validate,
                        kernel_type='linear')

Validate Set Accuracy: 0.5777777777777777
Test Set Accuracy: 0.5963938973647711

In [148]:
Cs = [c/10.0 for c in range(1, 10, 1)]

In [167]:
# changed mehtod parameters
for c in Cs:
    print(f'INFO: running classifier for linear kernel with C={c}')
    clf_linear = run_svm_nfl_predict(x_train_norm, y_train, 
                            x_test_norm, y_test, 
                            x_validate_norm, y_validate,
                            kernel_type='linear',
                            C_in=c)
    print()

INFO: running classifier for linear kernel with C=1.1
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.2
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.3
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.4
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.5
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.6
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.7
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.8
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.9
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.0
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.1
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.2
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.3
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.4
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.5
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

In [62]:
# 
# DONT DELETE, USES UNFLILTERED DATA
#
Cs = [c/100.0 for c in range(110, 260, 10)]
print(Cs)
# changed mehtod parameters
for c in Cs:
    print(f'INFO: running classifier for linear kernel with C={c}')
    clf_linear = run_svm_nfl_predict(x_train_norm, y_train, 
                            x_test_norm, y_test, 
                            x_validate_norm, y_validate,
                            kernel_type='linear',
                            C_in=c)
    print()

[1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5]
INFO: running classifier for linear kernel with C=1.1
Validate Set Accuracy: 0.5680555555555555
Test Set Accuracy: 0.5714285714285714

INFO: running classifier for linear kernel with C=1.2
Validate Set Accuracy: 0.5680555555555555
Test Set Accuracy: 0.5742024965325936

INFO: running classifier for linear kernel with C=1.3
Validate Set Accuracy: 0.5694444444444444
Test Set Accuracy: 0.5742024965325936

INFO: running classifier for linear kernel with C=1.4
Validate Set Accuracy: 0.5722222222222222
Test Set Accuracy: 0.579750346740638

INFO: running classifier for linear kernel with C=1.5
Validate Set Accuracy: 0.5722222222222222
Test Set Accuracy: 0.5811373092926491

INFO: running classifier for linear kernel with C=1.6
Validate Set Accuracy: 0.5736111111111111
Test Set Accuracy: 0.579750346740638

INFO: running classifier for linear kernel with C=1.7
Validate Set Accuracy: 0.5736111111111111
Test Set Accuracy: 0.5825242718446602

INFO: running classifier for linear kernel with C=1.8
Validate Set Accuracy: 0.5777777777777777
Test Set Accuracy: 0.5783633841886269

INFO: running classifier for linear kernel with C=1.9
Validate Set Accuracy: 0.5819444444444445
Test Set Accuracy: 0.579750346740638

INFO: running classifier for linear kernel with C=2.0
Validate Set Accuracy: 0.5819444444444445
Test Set Accuracy: 0.5783633841886269

INFO: running classifier for linear kernel with C=2.1
Validate Set Accuracy: 0.5805555555555556
Test Set Accuracy: 0.579750346740638

INFO: running classifier for linear kernel with C=2.2
Validate Set Accuracy: 0.5819444444444445
Test Set Accuracy: 0.5852981969486823

INFO: running classifier for linear kernel with C=2.3
Validate Set Accuracy: 0.5888888888888889
Test Set Accuracy: 0.5811373092926491

INFO: running classifier for linear kernel with C=2.4
Validate Set Accuracy: 0.5888888888888889
Test Set Accuracy: 0.5825242718446602

INFO: running classifier for linear kernel with C=2.5
Validate Set Accuracy: 0.5902777777777778
Test Set Accuracy: 0.5839112343966713

In [151]:
Cs = [c/100.0 for c in range(110, 260, 10)]
print(Cs)
# changed mehtod parameters
for c in Cs:
    print(f'INFO: running classifier for linear kernel with C={c}')
    clf_linear = run_svm_nfl_predict(x_train_norm, y_train, 
                            x_test_norm, y_test, 
                            x_validate_norm, y_validate,
                            kernel_type='linear',
                            C_in=c)
    print()

[1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5]
INFO: running classifier for linear kernel with C=1.1
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.2
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.3
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.4
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.5
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.6
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.7
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.8
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=1.9
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.0
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.1
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.2
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.3
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.4
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

INFO: running classifier for linear kernel with C=2.5
Validate Set Accuracy: 0.5638888888888889
Test Set Accuracy: 0.565880721220527

In [49]:
# 
# DONT DELETE, USES UNFLILTERED DATA
#
clf_rbf = run_svm_nfl_predict(x_train_norm, y_train, 
                        x_test_norm, y_test, 
                        x_validate_norm, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.6125
Test Set Accuracy: 0.5922330097087378

In [ ]:
#
# should play with the parameters of the radial basis function kernel
#
#TODO

In [50]:
clf_sigmoid = run_svm_nfl_predict(x_train_norm, y_train, 
                        x_test_norm, y_test, 
                        x_validate_norm, y_validate,
                        kernel_type='sigmoid')

Validate Set Accuracy: 0.5805555555555556
Test Set Accuracy: 0.5714285714285714

In [38]:
# 
# DONT DELETE, USES UNFLILTERED DATA
#

#
# rbf kernel with non-normalized features
#
clf_rbf_nonorm = run_svm_nfl_predict(x_train, y_train, 
                        x_test, y_test, 
                        x_validate, y_validate,
                        kernel_type='rbf')

Validate Set Accuracy: 0.5888888888888889
Test Set Accuracy: 0.5686546463245492

# Run MLP (NN)

In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

import numpy as np
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap

In [52]:
h = 0.02  # step size in the mesh

alphas = np.logspace(-1, 1, 5)

classifiers = []
names = []

In [56]:
for alpha in alphas:
    classifiers.append(
        make_pipeline(
            StandardScaler(),
            MLPClassifier(
                solver="lbfgs",
                alpha=alpha,
                random_state=1,
                max_iter=5000,
                early_stopping=True,
                hidden_layer_sizes=[10, 10],
            ),
        )
    )
    names.append(f"alpha {alpha:.2f}")

In [54]:
figure = plt.figure(figsize=(17, 9))

In [55]:
# iterate over classifiers
scores_d = dict()
for name, clf in zip(names, classifiers):
    clf.fit(x_train_norm, y_train)
    score = clf.score(x_test_norm, y_test)
    scores_d[name] = score
    
    '''
    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max] x [y_min, y_max].
    if hasattr(clf, "decision_function"):
        Z = clf.decision_function(np.column_stack([xx.ravel(), yy.ravel()]))
    else:
        Z = clf.predict_proba(np.column_stack([xx.ravel(), yy.ravel()]))[:, 1]
    '''
print(scores_d)

C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

{'alpha 0.10': 0.536754507628294, 'alpha 0.32': 0.5492371705963939, 'alpha 1.00': 0.5811373092926491, 'alpha 3.16': 0.5478502080443828, 'alpha 10.00': 0.5922330097087378}

C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

In [57]:
scores2_d = dict()
for name, clf in zip(names, classifiers):
    clf.fit(x_train_norm, y_train)
    score = clf.score(x_test_norm, y_test)
    scores2_d[name] = score
    
    '''
    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max] x [y_min, y_max].
    if hasattr(clf, "decision_function"):
        Z = clf.decision_function(np.column_stack([xx.ravel(), yy.ravel()]))
    else:
        Z = clf.predict_proba(np.column_stack([xx.ravel(), yy.ravel()]))[:, 1]
    '''
print(scores2_d)

C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\cocod\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:471: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

{'alpha 0.10': 0.536754507628294, 'alpha 0.32': 0.536754507628294, 'alpha 1.00': 0.5672676837725381, 'alpha 3.16': 0.5561719833564494, 'alpha 10.00': 0.5977808599167822}

In [58]:
print(cores_d)

{}